name: tide
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.12.0
  appwrite: ^21.4.0
  google_fonts: ^8.0.2
  camera: ^0.12.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  timeago: ^3.7.1
  share_plus: ^12.0.1
  video_player: ^2.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/tide__logo.png"
  adaptive_icon_background: "#FFFFFF" # Cor de fundo para Android
  adaptive_icon_foreground: "assets/images/tide__logo.png" # Camada da frente para Android
